import type { Metadata } from 'next';
import { Geist, Geist_Mono, Noto_Sans_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const notoSansMono = Noto_Sans_Mono({
	variable: '--font-noto-sans-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Anna Zoi',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${notoSansMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
